language: java
jdk:
  - oraclejdk8

sudo: false

install: true

script:
  - pwd
  - cd webapp/CloudApp
-pwd
-ls -al
  - ./mvnw clean install
  - cd build/libs
  - ls -al
  - cd ../../..
  - pwd
  - ls -al

after_success:
  - pwd
  - ls -al
  - mkdir codedeploy_artifact
  - cp infrastructure/aws/codedeploy/*.sh .
  - cp infrastructure/aws/codedeploy/*.yml .
  - zip -r csye6225-cloudapp.zip webapp/build/libs/ROOT.war *.sh *.yml
  - ls -al
  - mv csye6225-cloudapp.zip codedeploy_artifact/
  - ls -al
  - pwd
  - cd codedeploy_artifact
  - ls -al
  - pwd
  - cd ..
  - pwd
  - ls -al

deploy:
  - provider: s3
    local_dir: codedeploy_artifact
    bucket: $s3_bucket
    region: us-east-1
    skip_cleanup: true
    access_key_id: $access_key_id
    secret_access_key: $secret_access_key
    # on:
    #   branch: master
  - provider: codedeploy
    access_key_id: $access_key_id
    bucket: $s3_bucket
    key: csye6225-cloudapp.zip
    bundle_type: zip
    application: $application
    deployment_group: $deployment_group
    region: us-east-1
    # secret_access_key: $secret_access_key
    -wait-until-deployed: true
on:
      all_branches: true
