language: java
jdk:
  - oraclejdk8

sudo: false

install: true

script:
  - pwd
  - cd webapp/CloudApp
  - pwd
  - ls -al
  - mvn clean install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
  - cd target
  - ls -al
  - cd ../..
  - pwd
  - ls -al

after_success:
  - pwd
  - ls -al
  - cd ..
  - ls -al
  - mkdir codedeploy_artifact
  - pwd
  - ls -al
  - cd webapp/CloudApp/target
  - ls -al
  - cd ../../..
  - zip -r csye6225-cloudapp.zip . -i webapp/CloudApp/target/CloudApp.war 
  - ls -al
  - mv csye6225-cloudapp.zip codedeploy_artifact/
  - cd codedeploy_artifact
  - ls -al
  - pwd
  - ls -al
  - pwd
  - cd ..
  - pwd
  - ls -al

deploy:
  - provider: s3
    local_dir: codedeploy_artifact
    bucket: $s3_bucket
    region: us-east-1
    skip_cleanup: true
    access_key_id: $access_key_id
    secret_access_key: $secret_access_key
    on:
      branch: assignment5/6
  - provider: codedeploy
    access_key_id: $access_key_id
    bucket: $s3_bucket
    key: csye6225-cloudapp.zip
    bundle_type: zip
    application: $application
    deployment_group: $deployment_group
    region: us-east-1
    # secret_access_key: $secret_access_key
    -wait-until-deployed: true
on:
      all_branches: true
